// Generated by scripts/build-pronunciation-word-bank.mjs.

import type { PracticeDifficulty, PracticeSoundId } from "@/domain/pronunciation/practice";

export type PronunciationWordBankEntry = {
  soundId: PracticeSoundId;
  difficulty: PracticeDifficulty;
  text: string;
  targetLetters: string;
  highlightStart: number;
  highlightLength: number;
  targetArpabet: string;
  phones: string[];
  targetPhoneIndex: number;
  cmuVariant: number;
};

export const PRONUNCIATION_WORD_BANK: readonly PronunciationWordBankEntry[] = [
  {
    "soundId": "light_l",
    "difficulty": "easy",
    "text": "lake",
    "targetLetters": "l",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "L",
      "EY1",
      "K"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "easy",
    "text": "lamp",
    "targetLetters": "l",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "L",
      "AE1",
      "M",
      "P"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "easy",
    "text": "leaf",
    "targetLetters": "l",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "L",
      "IY1",
      "F"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "easy",
    "text": "leg",
    "targetLetters": "l",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "L",
      "EH1",
      "G"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "easy",
    "text": "lemon",
    "targetLetters": "l",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "L",
      "EH1",
      "M",
      "AH0",
      "N"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "easy",
    "text": "light",
    "targetLetters": "l",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "L",
      "AY1",
      "T"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "easy",
    "text": "lion",
    "targetLetters": "l",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "L",
      "AY1",
      "AH0",
      "N"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "easy",
    "text": "lip",
    "targetLetters": "l",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "L",
      "IH1",
      "P"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "easy",
    "text": "log",
    "targetLetters": "l",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "L",
      "AO1",
      "G"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "easy",
    "text": "love",
    "targetLetters": "l",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "L",
      "AH1",
      "V"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "medium",
    "text": "black",
    "targetLetters": "l",
    "highlightStart": 1,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "B",
      "L",
      "AE1",
      "K"
    ],
    "targetPhoneIndex": 1,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "medium",
    "text": "blue",
    "targetLetters": "l",
    "highlightStart": 1,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "B",
      "L",
      "UW1"
    ],
    "targetPhoneIndex": 1,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "medium",
    "text": "clean",
    "targetLetters": "l",
    "highlightStart": 1,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "K",
      "L",
      "IY1",
      "N"
    ],
    "targetPhoneIndex": 1,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "medium",
    "text": "clock",
    "targetLetters": "l",
    "highlightStart": 1,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "K",
      "L",
      "AA1",
      "K"
    ],
    "targetPhoneIndex": 1,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "medium",
    "text": "flag",
    "targetLetters": "l",
    "highlightStart": 1,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "F",
      "L",
      "AE1",
      "G"
    ],
    "targetPhoneIndex": 1,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "medium",
    "text": "fly",
    "targetLetters": "l",
    "highlightStart": 1,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "F",
      "L",
      "AY1"
    ],
    "targetPhoneIndex": 1,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "medium",
    "text": "glass",
    "targetLetters": "l",
    "highlightStart": 1,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "G",
      "L",
      "AE1",
      "S"
    ],
    "targetPhoneIndex": 1,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "medium",
    "text": "glue",
    "targetLetters": "l",
    "highlightStart": 1,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "G",
      "L",
      "UW1"
    ],
    "targetPhoneIndex": 1,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "medium",
    "text": "plane",
    "targetLetters": "l",
    "highlightStart": 1,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "P",
      "L",
      "EY1",
      "N"
    ],
    "targetPhoneIndex": 1,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "medium",
    "text": "play",
    "targetLetters": "l",
    "highlightStart": 1,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "P",
      "L",
      "EY1"
    ],
    "targetPhoneIndex": 1,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "hard",
    "text": "alive",
    "targetLetters": "l",
    "highlightStart": 1,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "AH0",
      "L",
      "AY1",
      "V"
    ],
    "targetPhoneIndex": 1,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "hard",
    "text": "balloon",
    "targetLetters": "ll",
    "highlightStart": 2,
    "highlightLength": 2,
    "targetArpabet": "L",
    "phones": [
      "B",
      "AH0",
      "L",
      "UW1",
      "N"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "hard",
    "text": "believe",
    "targetLetters": "l",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "B",
      "IH0",
      "L",
      "IY1",
      "V"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "hard",
    "text": "below",
    "targetLetters": "l",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "B",
      "IH0",
      "L",
      "OW1"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "hard",
    "text": "collect",
    "targetLetters": "ll",
    "highlightStart": 2,
    "highlightLength": 2,
    "targetArpabet": "L",
    "phones": [
      "K",
      "AH0",
      "L",
      "EH1",
      "K",
      "T"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "hard",
    "text": "color",
    "targetLetters": "l",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "K",
      "AH1",
      "L",
      "ER0"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "hard",
    "text": "delicious",
    "targetLetters": "l",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "D",
      "IH0",
      "L",
      "IH1",
      "SH",
      "AH0",
      "S"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "hard",
    "text": "electric",
    "targetLetters": "l",
    "highlightStart": 1,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "IH0",
      "L",
      "EH1",
      "K",
      "T",
      "R",
      "IH0",
      "K"
    ],
    "targetPhoneIndex": 1,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "hard",
    "text": "polite",
    "targetLetters": "l",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "P",
      "AH0",
      "L",
      "AY1",
      "T"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "light_l",
    "difficulty": "hard",
    "text": "select",
    "targetLetters": "l",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "L",
    "phones": [
      "S",
      "AH0",
      "L",
      "EH1",
      "K",
      "T"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "easy",
    "text": "bus",
    "targetLetters": "s",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "B",
      "AH1",
      "S"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "easy",
    "text": "face",
    "targetLetters": "c",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "F",
      "EY1",
      "S"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "easy",
    "text": "ice",
    "targetLetters": "c",
    "highlightStart": 1,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "AY1",
      "S"
    ],
    "targetPhoneIndex": 1,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "easy",
    "text": "mouse",
    "targetLetters": "s",
    "highlightStart": 3,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "M",
      "AW1",
      "S"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "easy",
    "text": "pencil",
    "targetLetters": "c",
    "highlightStart": 3,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "P",
      "EH1",
      "N",
      "S",
      "AH0",
      "L"
    ],
    "targetPhoneIndex": 3,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "easy",
    "text": "rice",
    "targetLetters": "c",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "R",
      "AY1",
      "S"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "easy",
    "text": "sit",
    "targetLetters": "s",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "S",
      "IH1",
      "T"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "easy",
    "text": "sock",
    "targetLetters": "s",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "S",
      "AA1",
      "K"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "easy",
    "text": "soup",
    "targetLetters": "s",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "S",
      "UW1",
      "P"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "easy",
    "text": "sun",
    "targetLetters": "s",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "S",
      "AH1",
      "N"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "medium",
    "text": "cent",
    "targetLetters": "c",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "S",
      "EH1",
      "N",
      "T"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "medium",
    "text": "circle",
    "targetLetters": "c",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "S",
      "ER1",
      "K",
      "AH0",
      "L"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "medium",
    "text": "city",
    "targetLetters": "c",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "S",
      "IH1",
      "T",
      "IY0"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "medium",
    "text": "dance",
    "targetLetters": "c",
    "highlightStart": 3,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "D",
      "AE1",
      "N",
      "S"
    ],
    "targetPhoneIndex": 3,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "medium",
    "text": "place",
    "targetLetters": "c",
    "highlightStart": 3,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "P",
      "L",
      "EY1",
      "S"
    ],
    "targetPhoneIndex": 3,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "medium",
    "text": "school",
    "targetLetters": "s",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "S",
      "K",
      "UW1",
      "L"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "medium",
    "text": "simple",
    "targetLetters": "s",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "S",
      "IH1",
      "M",
      "P",
      "AH0",
      "L"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "medium",
    "text": "smile",
    "targetLetters": "s",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "S",
      "M",
      "AY1",
      "L"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "medium",
    "text": "snake",
    "targetLetters": "s",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "S",
      "N",
      "EY1",
      "K"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "medium",
    "text": "star",
    "targetLetters": "s",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "S",
      "T",
      "AA1",
      "R"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "hard",
    "text": "answer",
    "targetLetters": "s",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "AE1",
      "N",
      "S",
      "ER0"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "hard",
    "text": "bicycle",
    "targetLetters": "c",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "B",
      "AY1",
      "S",
      "IH0",
      "K",
      "AH0",
      "L"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "hard",
    "text": "decide",
    "targetLetters": "c",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "D",
      "IH2",
      "S",
      "AY1",
      "D"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "hard",
    "text": "lesson",
    "targetLetters": "ss",
    "highlightStart": 2,
    "highlightLength": 2,
    "targetArpabet": "S",
    "phones": [
      "L",
      "EH1",
      "S",
      "AH0",
      "N"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "hard",
    "text": "listen",
    "targetLetters": "s",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "L",
      "IH1",
      "S",
      "AH0",
      "N"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "hard",
    "text": "medicine",
    "targetLetters": "c",
    "highlightStart": 4,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "M",
      "EH1",
      "D",
      "AH0",
      "S",
      "AH0",
      "N"
    ],
    "targetPhoneIndex": 4,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "hard",
    "text": "message",
    "targetLetters": "ss",
    "highlightStart": 2,
    "highlightLength": 2,
    "targetArpabet": "S",
    "phones": [
      "M",
      "EH1",
      "S",
      "AH0",
      "JH"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "hard",
    "text": "possible",
    "targetLetters": "ss",
    "highlightStart": 2,
    "highlightLength": 2,
    "targetArpabet": "S",
    "phones": [
      "P",
      "AA1",
      "S",
      "AH0",
      "B",
      "AH0",
      "L"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "hard",
    "text": "recent",
    "targetLetters": "c",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "R",
      "IY1",
      "S",
      "AH0",
      "N",
      "T"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "s",
    "difficulty": "hard",
    "text": "receive",
    "targetLetters": "c",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "S",
    "phones": [
      "R",
      "AH0",
      "S",
      "IY1",
      "V"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "easy",
    "text": "face",
    "targetLetters": "f",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "F",
    "phones": [
      "F",
      "EY1",
      "S"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "easy",
    "text": "fan",
    "targetLetters": "f",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "F",
    "phones": [
      "F",
      "AE1",
      "N"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "easy",
    "text": "fish",
    "targetLetters": "f",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "F",
    "phones": [
      "F",
      "IH1",
      "SH"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "easy",
    "text": "five",
    "targetLetters": "f",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "F",
    "phones": [
      "F",
      "AY1",
      "V"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "easy",
    "text": "food",
    "targetLetters": "f",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "F",
    "phones": [
      "F",
      "UW1",
      "D"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "easy",
    "text": "foot",
    "targetLetters": "f",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "F",
    "phones": [
      "F",
      "UH1",
      "T"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "easy",
    "text": "fork",
    "targetLetters": "f",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "F",
    "phones": [
      "F",
      "AO1",
      "R",
      "K"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "easy",
    "text": "four",
    "targetLetters": "f",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "F",
    "phones": [
      "F",
      "AO1",
      "R"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "easy",
    "text": "leaf",
    "targetLetters": "f",
    "highlightStart": 3,
    "highlightLength": 1,
    "targetArpabet": "F",
    "phones": [
      "L",
      "IY1",
      "F"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "easy",
    "text": "roof",
    "targetLetters": "f",
    "highlightStart": 3,
    "highlightLength": 1,
    "targetArpabet": "F",
    "phones": [
      "R",
      "UW1",
      "F"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "medium",
    "text": "after",
    "targetLetters": "f",
    "highlightStart": 1,
    "highlightLength": 1,
    "targetArpabet": "F",
    "phones": [
      "AE1",
      "F",
      "T",
      "ER0"
    ],
    "targetPhoneIndex": 1,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "medium",
    "text": "before",
    "targetLetters": "f",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "F",
    "phones": [
      "B",
      "IH0",
      "F",
      "AO1",
      "R"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "medium",
    "text": "coffee",
    "targetLetters": "ff",
    "highlightStart": 2,
    "highlightLength": 2,
    "targetArpabet": "F",
    "phones": [
      "K",
      "AA1",
      "F",
      "IY0"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "medium",
    "text": "dolphin",
    "targetLetters": "ph",
    "highlightStart": 3,
    "highlightLength": 2,
    "targetArpabet": "F",
    "phones": [
      "D",
      "AA1",
      "L",
      "F",
      "AH0",
      "N"
    ],
    "targetPhoneIndex": 3,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "medium",
    "text": "elephant",
    "targetLetters": "ph",
    "highlightStart": 3,
    "highlightLength": 2,
    "targetArpabet": "F",
    "phones": [
      "EH1",
      "L",
      "AH0",
      "F",
      "AH0",
      "N",
      "T"
    ],
    "targetPhoneIndex": 3,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "medium",
    "text": "enough",
    "targetLetters": "gh",
    "highlightStart": 4,
    "highlightLength": 2,
    "targetArpabet": "F",
    "phones": [
      "IH0",
      "N",
      "AH1",
      "F"
    ],
    "targetPhoneIndex": 3,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "medium",
    "text": "laugh",
    "targetLetters": "gh",
    "highlightStart": 3,
    "highlightLength": 2,
    "targetArpabet": "F",
    "phones": [
      "L",
      "AE1",
      "F"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "medium",
    "text": "phone",
    "targetLetters": "ph",
    "highlightStart": 0,
    "highlightLength": 2,
    "targetArpabet": "F",
    "phones": [
      "F",
      "OW1",
      "N"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "medium",
    "text": "photo",
    "targetLetters": "ph",
    "highlightStart": 0,
    "highlightLength": 2,
    "targetArpabet": "F",
    "phones": [
      "F",
      "OW1",
      "T",
      "OW2"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "medium",
    "text": "safe",
    "targetLetters": "f",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "F",
    "phones": [
      "S",
      "EY1",
      "F"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "hard",
    "text": "alphabet",
    "targetLetters": "ph",
    "highlightStart": 2,
    "highlightLength": 2,
    "targetArpabet": "F",
    "phones": [
      "AE1",
      "L",
      "F",
      "AH0",
      "B",
      "EH2",
      "T"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "hard",
    "text": "breakfast",
    "targetLetters": "f",
    "highlightStart": 5,
    "highlightLength": 1,
    "targetArpabet": "F",
    "phones": [
      "B",
      "R",
      "EH1",
      "K",
      "F",
      "AH0",
      "S",
      "T"
    ],
    "targetPhoneIndex": 4,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "hard",
    "text": "different",
    "targetLetters": "ff",
    "highlightStart": 2,
    "highlightLength": 2,
    "targetArpabet": "F",
    "phones": [
      "D",
      "IH1",
      "F",
      "ER0",
      "AH0",
      "N",
      "T"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "hard",
    "text": "favorite",
    "targetLetters": "f",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "F",
    "phones": [
      "F",
      "EY1",
      "V",
      "ER0",
      "IH0",
      "T"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "hard",
    "text": "finish",
    "targetLetters": "f",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "F",
    "phones": [
      "F",
      "IH1",
      "N",
      "IH0",
      "SH"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "hard",
    "text": "flower",
    "targetLetters": "f",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "F",
    "phones": [
      "F",
      "L",
      "AW1",
      "ER0"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "hard",
    "text": "office",
    "targetLetters": "ff",
    "highlightStart": 1,
    "highlightLength": 2,
    "targetArpabet": "F",
    "phones": [
      "AO1",
      "F",
      "AH0",
      "S"
    ],
    "targetPhoneIndex": 1,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "hard",
    "text": "perfect",
    "targetLetters": "f",
    "highlightStart": 3,
    "highlightLength": 1,
    "targetArpabet": "F",
    "phones": [
      "P",
      "ER0",
      "F",
      "EH1",
      "K",
      "T"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "hard",
    "text": "traffic",
    "targetLetters": "ff",
    "highlightStart": 3,
    "highlightLength": 2,
    "targetArpabet": "F",
    "phones": [
      "T",
      "R",
      "AE1",
      "F",
      "IH0",
      "K"
    ],
    "targetPhoneIndex": 3,
    "cmuVariant": 1
  },
  {
    "soundId": "f",
    "difficulty": "hard",
    "text": "trophy",
    "targetLetters": "ph",
    "highlightStart": 3,
    "highlightLength": 2,
    "targetArpabet": "F",
    "phones": [
      "T",
      "R",
      "OW1",
      "F",
      "IY0"
    ],
    "targetPhoneIndex": 3,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "easy",
    "text": "five",
    "targetLetters": "v",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "F",
      "AY1",
      "V"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "easy",
    "text": "love",
    "targetLetters": "v",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "L",
      "AH1",
      "V"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "easy",
    "text": "save",
    "targetLetters": "v",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "S",
      "EY1",
      "V"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "easy",
    "text": "seven",
    "targetLetters": "v",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "S",
      "EH1",
      "V",
      "AH0",
      "N"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "easy",
    "text": "van",
    "targetLetters": "v",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "V",
      "AE1",
      "N"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "easy",
    "text": "vase",
    "targetLetters": "v",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "V",
      "EY1",
      "S"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "easy",
    "text": "very",
    "targetLetters": "v",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "V",
      "EH1",
      "R",
      "IY0"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "easy",
    "text": "vest",
    "targetLetters": "v",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "V",
      "EH1",
      "S",
      "T"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "easy",
    "text": "vet",
    "targetLetters": "v",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "V",
      "EH1",
      "T"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "easy",
    "text": "wave",
    "targetLetters": "v",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "W",
      "EY1",
      "V"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "medium",
    "text": "drive",
    "targetLetters": "v",
    "highlightStart": 3,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "D",
      "R",
      "AY1",
      "V"
    ],
    "targetPhoneIndex": 3,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "medium",
    "text": "even",
    "targetLetters": "v",
    "highlightStart": 1,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "IY1",
      "V",
      "IH0",
      "N"
    ],
    "targetPhoneIndex": 1,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "medium",
    "text": "glove",
    "targetLetters": "v",
    "highlightStart": 3,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "G",
      "L",
      "AH1",
      "V"
    ],
    "targetPhoneIndex": 3,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "medium",
    "text": "heavy",
    "targetLetters": "v",
    "highlightStart": 3,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "HH",
      "EH1",
      "V",
      "IY0"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "medium",
    "text": "movie",
    "targetLetters": "v",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "M",
      "UW1",
      "V",
      "IY0"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "medium",
    "text": "never",
    "targetLetters": "v",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "N",
      "EH1",
      "V",
      "ER0"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "medium",
    "text": "over",
    "targetLetters": "v",
    "highlightStart": 1,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "OW1",
      "V",
      "ER0"
    ],
    "targetPhoneIndex": 1,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "medium",
    "text": "river",
    "targetLetters": "v",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "R",
      "IH1",
      "V",
      "ER0"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "medium",
    "text": "visit",
    "targetLetters": "v",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "V",
      "IH1",
      "Z",
      "IH0",
      "T"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "medium",
    "text": "voice",
    "targetLetters": "v",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "V",
      "OY1",
      "S"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "hard",
    "text": "arrive",
    "targetLetters": "v",
    "highlightStart": 4,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "ER0",
      "AY1",
      "V"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "hard",
    "text": "avoid",
    "targetLetters": "v",
    "highlightStart": 1,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "AH0",
      "V",
      "OY1",
      "D"
    ],
    "targetPhoneIndex": 1,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "hard",
    "text": "clever",
    "targetLetters": "v",
    "highlightStart": 3,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "K",
      "L",
      "EH1",
      "V",
      "ER0"
    ],
    "targetPhoneIndex": 3,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "hard",
    "text": "cover",
    "targetLetters": "v",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "K",
      "AH1",
      "V",
      "ER0"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "hard",
    "text": "every",
    "targetLetters": "v",
    "highlightStart": 1,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "EH1",
      "V",
      "ER0",
      "IY0"
    ],
    "targetPhoneIndex": 1,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "hard",
    "text": "favorite",
    "targetLetters": "v",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "F",
      "EY1",
      "V",
      "ER0",
      "IH0",
      "T"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "hard",
    "text": "invite",
    "targetLetters": "v",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "IH0",
      "N",
      "V",
      "AY1",
      "T"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "hard",
    "text": "leave",
    "targetLetters": "v",
    "highlightStart": 3,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "L",
      "IY1",
      "V"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "hard",
    "text": "private",
    "targetLetters": "v",
    "highlightStart": 3,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "P",
      "R",
      "AY1",
      "V",
      "AH0",
      "T"
    ],
    "targetPhoneIndex": 3,
    "cmuVariant": 1
  },
  {
    "soundId": "v",
    "difficulty": "hard",
    "text": "travel",
    "targetLetters": "v",
    "highlightStart": 3,
    "highlightLength": 1,
    "targetArpabet": "V",
    "phones": [
      "T",
      "R",
      "AE1",
      "V",
      "AH0",
      "L"
    ],
    "targetPhoneIndex": 3,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "easy",
    "text": "cheese",
    "targetLetters": "s",
    "highlightStart": 4,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "CH",
      "IY1",
      "Z"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "easy",
    "text": "eyes",
    "targetLetters": "s",
    "highlightStart": 3,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "AY1",
      "Z"
    ],
    "targetPhoneIndex": 1,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "easy",
    "text": "lazy",
    "targetLetters": "z",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "L",
      "EY1",
      "Z",
      "IY0"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "easy",
    "text": "music",
    "targetLetters": "s",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "M",
      "Y",
      "UW1",
      "Z",
      "IH0",
      "K"
    ],
    "targetPhoneIndex": 3,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "easy",
    "text": "nose",
    "targetLetters": "s",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "N",
      "OW1",
      "Z"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "easy",
    "text": "rose",
    "targetLetters": "s",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "R",
      "OW1",
      "Z"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "easy",
    "text": "zebra",
    "targetLetters": "z",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "Z",
      "IY1",
      "B",
      "R",
      "AH0"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "easy",
    "text": "zero",
    "targetLetters": "z",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "Z",
      "IH1",
      "R",
      "OW0"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "easy",
    "text": "zip",
    "targetLetters": "z",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "Z",
      "IH1",
      "P"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "easy",
    "text": "zoo",
    "targetLetters": "z",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "Z",
      "UW1"
    ],
    "targetPhoneIndex": 0,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "medium",
    "text": "busy",
    "targetLetters": "s",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "B",
      "IH1",
      "Z",
      "IY0"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "medium",
    "text": "cousin",
    "targetLetters": "s",
    "highlightStart": 3,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "K",
      "AH1",
      "Z",
      "AH0",
      "N"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "medium",
    "text": "dozen",
    "targetLetters": "z",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "D",
      "AH1",
      "Z",
      "AH0",
      "N"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "medium",
    "text": "easy",
    "targetLetters": "s",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "IY1",
      "Z",
      "IY0"
    ],
    "targetPhoneIndex": 1,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "medium",
    "text": "frozen",
    "targetLetters": "z",
    "highlightStart": 3,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "F",
      "R",
      "OW1",
      "Z",
      "AH0",
      "N"
    ],
    "targetPhoneIndex": 3,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "medium",
    "text": "puzzle",
    "targetLetters": "zz",
    "highlightStart": 2,
    "highlightLength": 2,
    "targetArpabet": "Z",
    "phones": [
      "P",
      "AH1",
      "Z",
      "AH0",
      "L"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "medium",
    "text": "reason",
    "targetLetters": "s",
    "highlightStart": 3,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "R",
      "IY1",
      "Z",
      "AH0",
      "N"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "medium",
    "text": "season",
    "targetLetters": "s",
    "highlightStart": 0,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "S",
      "IY1",
      "Z",
      "AH0",
      "N"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "medium",
    "text": "visit",
    "targetLetters": "s",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "V",
      "IH1",
      "Z",
      "IH0",
      "T"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "medium",
    "text": "wizard",
    "targetLetters": "z",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "W",
      "IH1",
      "Z",
      "ER0",
      "D"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "hard",
    "text": "amazing",
    "targetLetters": "z",
    "highlightStart": 3,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "AH0",
      "M",
      "EY1",
      "Z",
      "IH0",
      "NG"
    ],
    "targetPhoneIndex": 3,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "hard",
    "text": "because",
    "targetLetters": "s",
    "highlightStart": 5,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "B",
      "IH0",
      "K",
      "AO1",
      "Z"
    ],
    "targetPhoneIndex": 4,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "hard",
    "text": "dessert",
    "targetLetters": "ss",
    "highlightStart": 2,
    "highlightLength": 2,
    "targetArpabet": "Z",
    "phones": [
      "D",
      "IH0",
      "Z",
      "ER1",
      "T"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "hard",
    "text": "design",
    "targetLetters": "s",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "D",
      "IH0",
      "Z",
      "AY1",
      "N"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "hard",
    "text": "dizzy",
    "targetLetters": "zz",
    "highlightStart": 2,
    "highlightLength": 2,
    "targetArpabet": "Z",
    "phones": [
      "D",
      "IH1",
      "Z",
      "IY0"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "hard",
    "text": "magazine",
    "targetLetters": "z",
    "highlightStart": 4,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "M",
      "AE1",
      "G",
      "AH0",
      "Z",
      "IY2",
      "N"
    ],
    "targetPhoneIndex": 4,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "hard",
    "text": "organize",
    "targetLetters": "z",
    "highlightStart": 6,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "AO1",
      "R",
      "G",
      "AH0",
      "N",
      "AY2",
      "Z"
    ],
    "targetPhoneIndex": 6,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "hard",
    "text": "realize",
    "targetLetters": "z",
    "highlightStart": 5,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "R",
      "IY1",
      "AH0",
      "L",
      "AY2",
      "Z"
    ],
    "targetPhoneIndex": 5,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "hard",
    "text": "result",
    "targetLetters": "s",
    "highlightStart": 2,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "R",
      "IH0",
      "Z",
      "AH1",
      "L",
      "T"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  },
  {
    "soundId": "z",
    "difficulty": "hard",
    "text": "tuesday",
    "targetLetters": "s",
    "highlightStart": 3,
    "highlightLength": 1,
    "targetArpabet": "Z",
    "phones": [
      "T",
      "UW1",
      "Z",
      "D",
      "IY0"
    ],
    "targetPhoneIndex": 2,
    "cmuVariant": 1
  }
];
